### ISSUE TITLE
Scrolling issues in ipads with new ASG version

### ISSUE THREAD

**Issue by starchild** [CodyHouse/cd-auto-sized-grid-changelog#2]
Ok, so this is a bit of a curly one.  We use codeframe in our custom ecommerce framework - We use auto-size-grid in our shopping category pages.

To date, we've been using v1 and have just changed to 2.91

In doing so, we have had many complaints from ipad users who say that the pages are jumping around all over the place now  when scrolling.  I notice even o my new M1 ipad, that scrolling often causes the screen to go white and then it kind of redraws itself.

I've tested a bunch of things and when I revert to v1, the issue disappears.  So I'm assuming here that the new component version has some issue.

It happens in both safari and chrome.  I'm currently on iOS14.

Many clients have older ipads and the issue is even more pronounced.

We're looking at some kind of ipad-detect function to serve the old version but I really don't want to have to do this.

Is this something you're aware of?

Thank you.

**Comment by starchild** [comment]
I tried simply swapping out the css for that plugin but it didn't fix the issue.  So I guess the issue lies elsewhere within the framework?

**Comment by claudia-romano** [comment]
Hi there, 
we didn't have any complains about this kind of bug. 

There were major changes with CodyFrame v2, for example some classes were deprecated. Is this something you checked before upgrading from v1 to v2?

If you did, then can you try to recreate the bug using our framework without custom code (e.g., your ecommerce functions) that may be the reason for the bug?

I'm closing this issue as it is not related to the Auto Sized Grid component. Feel free to open a new issue on the framework page as soon as you can recreate the bug. Thank you.

**Comment by starchild** [comment]
Yes, I believe you are right.  I'm trying to isolate the issue now.  Sorry for the time waste.
